name: go vet test

on:
  push:

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
    
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24'
            
        - name: Verify dependencies
          run: go mod verify

        - name: Install staticcheck
          run: go install honnef.co/go/tools/cmd/staticcheck@latest

        - name: Run go vet
          run: make vet

        - name: Run make lint
          run: make lint

    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.24'

          - name: Run make test
            run: make test